openradar/xradar

LICENSE, docs/usage.md
Add "Open Radar Community Developers" to the license
=> ENH: Make license more general

docs/conf.py, docs/history.md
For some reason the tagged versions (eg. 0.0.6) are not correctly installed. This version shows up as `0.0.7.dev0+g8f2753a.d20220920`.
This PR checks the commit on RTD and pip installs that commit directly from github. 
~This might break for PR builds, which we would need to detect and prepare for.~
This looks like it works nicely also for PR builds.
=> Fix version on ReadTheDocs

.github/workflows/ci.yml, ci/unittests.yml, environment.yml, examples/notebooks/Accessors.ipynb, examples/notebooks/CfRadial1.ipynb, examples/notebooks/CfRadial1_full.ipynb, examples/notebooks/Furuno.ipynb, examples/notebooks/GAMIC.ipynb, examples/notebooks/GAMIC_full.ipynb, examples/notebooks/Iris.ipynb, examples/notebooks/Iris_full.ipynb, examples/notebooks/ODIM_H5.ipynb, examples/notebooks/ODIM_H5_full.ipynb, examples/notebooks/Rainbow.ipynb, examples/notebooks/Rainbow_full.ipynb, examples/notebooks/conftest.py, examples/notebooks/plot-ppi.ipynb, tests/conftest.py, tests/test_io.py, xradar/accessors.py, xradar/io/backends/cfradial1.py, xradar/io/backends/furuno.py, xradar/io/backends/gamic.py, xradar/io/backends/iris.py, xradar/io/backends/odim.py, xradar/io/backends/rainbow.py
- fetch radar data from open-radar-data
- add description/url to BackendEntrypoints
- test notebooks, fixup CI
=> MNT: fetch radar data from open-radar-data, add description/url

.pre-commit-config.yaml, docs/usage.md, examples/notebooks/Accessors.ipynb, examples/notebooks/CfRadial1.ipynb, examples/notebooks/CfRadial1_Model_Transformation.ipynb, examples/notebooks/CfRadial1_full.ipynb, examples/notebooks/Furuno.ipynb, examples/notebooks/GAMIC.ipynb, examples/notebooks/GAMIC_full.ipynb, examples/notebooks/Iris.ipynb, examples/notebooks/Iris_full.ipynb, examples/notebooks/ODIM_H5.ipynb, examples/notebooks/ODIM_H5_full.ipynb, examples/notebooks/Rainbow.ipynb, examples/notebooks/Rainbow_full.ipynb, examples/notebooks/plot-ppi.ipynb, tests/test_io.py, xradar/georeference/transforms.py, xradar/io/backends/cfradial1.py, xradar/io/backends/gamic.py, xradar/io/backends/iris.py, xradar/io/backends/odim.py, xradar/io/backends/rainbow.py, xradar/io/export.py, xradar/model.py
This is an attempt to increase the amount of metadata which is imported into the internal DataTree-structure at the right places CfRadial2 is expecting it.
Takes over from: #43 
- refactor internal cfradial1 reader to extract CfRadial2 groups from cfradial1 Dataset
- enhance the model with subgroup metadata
- fix tests
- add Notebook showing the transformation from CfRadial1 to CfRadial2
- fix Notebooks and tests
ToDo:
- Make the above happen also for sweep-subgroups (need to have example files).
- Make the above happen also for other sources (`ODIM_H5`, etc), the transformation might not be that easy, though. But in any case a notebook writeup showing the transformation would help developers and users to look behind the scenes.
=> ENH: Generalize CfRadial1 reader

examples/notebooks/CfRadial1.ipynb, examples/notebooks/CfRadial1_Model_Transformation.ipynb, examples/notebooks/CfRadial1_full.ipynb, tests/test_io.py, xradar/io/backends/cfradial1.py, xradar/io/export/__init__.py, xradar/io/export/cfradial2.py, xradar/io/export/odim.py, xradar/model.py
1. CfRadial1 reader kwarg refactor:
```python
"""
first_dim : str
Can be ``time`` or ``auto`` first dimension. If set to ``auto``,
first dimension will be either ``azimuth`` or ``elevation`` depending on
type of sweep. Defaults to ``auto``.
optional : bool
Import optional mandatory data and metadata, defaults to ``True``.
site_coords : bool
Attach radar site-coordinates to Dataset, defaults to ``True``.
"""
```
```python
swp = xr.open_dataset(fname, group="sweep_0", site_coords=False, optional=False, first_dim="time", engine="cfradial1")
```
These kwargs are available for DataTree loading, as well as Dataset-loading.
2. Add `to_cfradial2` export function
- added functionality to model to conform a sweep dataset, such that only CfRadial2 conforming data is written (needs extension and …
=> CfRadial1 reader kwargs refactor, add to_cfradial2 exporter 

CITATION.cff, README.md, ci/unittests.yml, docs/exporters.md, docs/history.md, docs/usage.md, environment.yml, requirements.txt, setup.py, tox.ini
How about releasing the recent changes as xradar v0.0.9?
I'm eager to test the newly added functionality over at `wradlib`. I'm feeling that xradar backends related code might already be in a usable state.
In this PR I've added documentation and did some tweaks to the package metadata. @mgrover1 please add to the below list of todo's or just push any necessary changes to this branch.
Todo:
=> REL: 0.0.9

tests/io/test_iris.py, xradar/io/backends/iris.py
closes #78 
Unfortunately the description in the docs is inaccurate. I've taken a reasonable approach to decode as probably intended.
> **4.4.42 1-byte Unfolded Velocity Format (DB_VELC)**
>
> This is the mean radial velocity corrected for both Nyquist folding and fall speed. It is scaled
> to cover a fixed span of +/- 75 meters/second. In data product files, the value 255 is used to
> indicate area not scanned.
> 
> 0 | Velocity data not available at this range
> 1 | -75.0 m/s (towards the radar)
> 2 | -74.4 m/s
> 128 | Zero velocity
> 129 | +0.6 m/s
> 254 | +75.0 m/s (away from the radar)
> 255 | Area not scanned
This will now be decoded to:
[ inf, -75., -74.409449,  0.,   0.590551, 74.409449,  75.]
=> ENH: add IRIS DB_VELC decoding and tests

tests/io/test_io.py, xradar/io/backends/furuno.py
closes #77 
fixes several issues with the furuno backend
=> FIX: furuno backend inconsistencies

CITATION.cff, docs/history.md
Moving forward with releasing the latest changes.
Let's keep up momentum in getting `xradar` as a first class citizen into `wradlib`. :rocket:
=> REL: 0.0.12

xradar/io/backends/odim.py
So this is unfortunate, as this slipped through the cracks. But anyway version numbers are cheap. :man_facepalming:
=> FIX: only skip setting cf-attributes if both gain and offset are unused

.pre-commit-config.yaml, ci/unittests.yml, docs/datamodel.md, environment.yml, examples/notebooks/CfRadial1.ipynb, examples/notebooks/GAMIC.ipynb, examples/notebooks/Iris.ipynb, examples/notebooks/Rainbow.ipynb, examples/notebooks/angle_reindexing.ipynb, examples/notebooks/plot-ppi.ipynb, requirements.txt, tests/georeference/test_projection.py, tests/georeference/test_transforms.py, tests/test_accessors.py, tests/test_model.py, tox.ini, xradar/accessors.py, xradar/georeference/__init__.py, xradar/georeference/projection.py, xradar/georeference/transforms.py, xradar/model.py
This adds `spatial_ref` to the datasets when georeferencing. That way users can easily wrap this into cartopy and use this for georeferenced plotting.
- tests added/adapted
- added example to plot-ppi.ipynb notebook
- takes site coordinates into account (altitude) for georeferencing
- site coordinates are in default model Dataset (Locarno Monti, MeteoSvizzera coords, birthplace of xradar)
=> ENH: add `spatial_ref` with `pyproj` when georeferencing, add/adapt methods/tests

docs/history.md, tests/io/test_io.py, xradar/io/export/cfradial2.py, xradar/model.py
=> FIX: check for dim0 if not given, only swap_dims if needed

docs/history.md, tests/io/test_io.py, xradar/io/export/odim.py
This fixes an issue when writing `to_odim` if the underlying data array's write flag wasn't set. It also adds the capability to add `compression`/`compression_opts` kwargs in the call to `to_odim`.
The latter makes it very easy and convenient to use the [zoo of compressors](https://portal.hdfgroup.org/display/support/Registered+Filter+Plugins) available to `hdf5`. Please refer to http://www.silx.org/doc/hdf5plugin/latest/index.html for usage examples.
=> ENH: make copy before overwriting, add compression in to_odim

docs/history.md, tests/io/test_io.py, xradar/io/export/odim.py
Now by default the function to_odim writes only mandatory metadata. There is a new option to add recommended metadata. See ODIM documentation for more information.
Note that only a few recommended metadata can be written at the moment.
=> ENH: switch to add recommended metadata

docs/history.md, xradar/io/backends/iris.py
Update: 
A bit more context here, we've just stumbled over these types in the wild. I've had a look into the docs/code and they are referenced as:
```
DB_DBTE8         = 71,  /* Total Power Enhanced (via H+V or HV) (1 byte) */
DB_DBTE16        = 72,  /* Total Power Enhanced (via H+V or HV) (2 byte) */
DB_DBZE8         = 73,  /* Clutter Corrected Reflectivity Enhanced (1 byte) */
DB_DBZE16        = 74,  /* Clutter Corrected Reflectivity Enhanced (2 byte) */
```
I've not added this to the moments mapping (attributes). So for now no attributes will be added. We'll gather more information before adding these attributes.
=> FIX: Correct DB_DBTE8/DB_DBZE8 and DB_DBTE16/DB_DBZE16 decoding

docs/history.md, xradar/io/backends/rainbow.py
Currently a boolean string value of "0" in the Rainbow file (e.g. antdirection) is converted to True instead of False.
bool("0") => True
=> FIX: Cast boolean string to int in rainbow dictionary

docs/history.md, tests/test_util.py, xradar/io/backends/cfradial1.py, xradar/io/backends/furuno.py, xradar/io/backends/gamic.py, xradar/io/backends/iris.py, xradar/io/backends/odim.py, xradar/io/backends/rainbow.py, xradar/model.py, xradar/util.py
As reported by @egouden in #114 there are issues with time interpolation in some corner cases. While adding a test for this I've found there are more things involved which need changing. This PR addresses (hopefully) all of this.
- only interpolate of NaT present
- handle NaT correctly (-9223372036854775808)
- handle a1gate properly (roll data to first measured ray)
- derive interpolation angles using diff
- handle wrap around angles for PPI
- fix spurious digits introduced by floating point interpolation
Supersedes #114
=> FIX: time_interpolation

docs/history.md, tests/test_util.py, xradar/util.py
=> FIX: implement more robust angle_res retrieval

CITATION.cff, docs/history.md, xradar/io/export/odim.py
=> Fix odim output/ rel 0.3.0

docs/history.md, tests/georeference/test_projection.py, tests/georeference/test_transforms.py, xradar/io/backends/iris.py
=> FIX: use datastore._group instead of variable["sweep_number"]

docs/history.md, tests/georeference/test_projection.py, tests/georeference/test_transforms.py, xradar/georeference/projection.py
This forces writing of `crs_wkt` instead of deprecated `spatial_ref`. On reading `crs_wkt` takes precedence over `spatial_ref` (for backwards compatibility).
=> use `crs_wkt` instead of deprecated `spatial_ref`

xradar/io/backends/odim.py
The current behavior is to not read ODIM _undetect_ and _nodata_ attributes if the values are not transformed (i.e. the attribute _gain_ is 1 and the attribute _offset_ is 0). This can lead to a loss of information. I think these attributes should always be read.
=> FIX: always read nodata and undetect attributes from ODIM file

docs/conf.py, docs/exporters.md, docs/history.md, docs/importers.md, docs/usage.md, environment.yml
=> FIX: fix sphinx-favicon, fix sphinx-extlinks to get readthedocs running

docs/history.md, xradar/io/backends/furuno.py
=> FIX: prevent integer overflow when calculating azimuth in FURUNO scn files

docs/history.md, xradar/georeference/projection.py
Currently this will always return AEQD crs instead of the one in crs_wkt since the current check just checks for `True`. It fails since crs_wkt is a variable with value 0.
=> FIX: explicitely check for "False" in get_crs()

.github/workflows/ci.yml, .github/workflows/upload_pypi.yml, docs/history.md, pyproject.toml, tests/io/test_io.py, tests/test_model.py, tests/test_util.py, xradar/io/backends/cfradial1.py, xradar/io/export/cfradial1.py, xradar/io/export/odim.py
=> MNT: Update GitHub actions, address DeprecationWarnings

.github/workflows/ci.yml, docs/history.md
Tokenless coverage upload is only available for PR with latest codecov-action. This adds the token to the CI run, to upload coverage on merges etc. Token is already present in repo secrets.
=> MNT: use CODECOV token

.github/workflows/ci.yml, docs/history.md, examples/notebooks/conftest.py
=> MNT: fix path for notebook coverage

docs/history.md, tests/io/test_nexrad_level2.py, xradar/io/backends/nexrad_level2.py
Ensure the elevation angle is unpacked into the fixed angle variable, giving a numerical value instead of the ordered dictionary
=> FIX: Add the proper elevation angle to fixed angle

docs/history.md, tests/test_util.py, xradar/util.py
Add a utility to find the `sweep_n` keys in a given datatree. This will help with downstream applications, especially with Py-ART, and since this information will be stored in the core data model.
=> ENH: Add a utility for finding sweep number keys

AUTHORS.md, docs/history.md, examples/notebooks/multiple-sweeps-into-volume-scan.ipynb, tests/io/test_io.py, xradar/io/backends/iris.py
adding radar parameters to xradar iris datatree
=> adding radar parameters to xradar iris datatree

CITATION.cff, docs/history.md
Add @aladinor to the citation document, which will ensure he is listed in the Zenodo DOI.
=> ADD: Add Alfonso to citation doc

docs/history.md, xradar/io/export/odim.py
=> FIX: set fillvalue before applying scale/offset when exporting odim

.github/workflows/ci.yml, docs/history.md, examples/notebooks/NexradLevel2.ipynb, examples/notebooks/ODIM_H5.ipynb, examples/notebooks/conftest.py, tests/io/test_io.py, xradar/io/backends/iris.py, xradar/io/backends/rainbow.py
=> FIX: Fix use of ruff, CI and numpy2

ci/notebooktests.yml, ci/unittests.yml, docs/history.md, tests/conftest.py, tests/io/test_io.py, xradar/io/backends/cfradial1.py, xradar/model.py
=> FIX: properly read CfRadial1 n_points files

docs/history.md, xradar/io/backends/cfradial1.py
=> changing open_cfradial1_datatree engine from 'netcdf4' to 'h5netcdf'

docs/history.md, tests/io/test_datamet.py, xradar/io/backends/datamet.py
=> FIX: do not apply scale/offset in datamet reader, leave it to xarray instead

.github/workflows/ci.yml, tests/conftest.py, tests/io/test_datamet.py, tests/io/test_hpl.py, tests/io/test_io.py, tests/io/test_nexrad_level2.py, tests/test_model.py
… should finally resolve annoying bus error in CI
=> FIX: testsuite

.github/workflows/ci.yml
This enables the testing of the `xarray-nightly` branch as an additional CI run. When next xarray-version is out, we can merge the feature branch into main. 
With minor adaptions to the pinnings this should then work as in the additional run here.
=> Add xarray nightly CI run

docs/history.md, tests/io/test_iris.py, tests/test_xradar.py
=> ADD: pytests to missing funcs

docs/history.md, tests/io/test_datamet.py, tests/io/test_furuno.py, tests/io/test_gamic.py, tests/io/test_hpl.py, tests/io/test_iris.py, tests/io/test_metek.py, tests/io/test_nexrad_level2.py, tests/io/test_odim.py, tests/io/test_rainbow.py, xradar/io/backends/nexrad_level2.py
=> ADD: Add scan_name to nexrad datatree attributes

.github/workflows/ci.yml, ci/notebooktests.yml, ci/unittests.yml, docs/history.md, examples/notebooks/HaloPhotonics.ipynb, examples/notebooks/conftest.py, tests/io/test_hpl.py, xradar/io/backends/hpl.py
This fixes the error shown in PR #247 when an RHI was being loaded by the Halo Photonics reader.
=> FIX: RHIs now work with Halo Photonics Reader

docs/history.md, examples/notebooks/HaloPhotonics.ipynb, examples/notebooks/conftest.py, xradar/io/backends/common.py, xradar/io/backends/hpl.py, xradar/io/backends/nexrad_level2.py
fixing IndexError when opening nexrad Split Cut Mode file
=> fixing IndexError when opening nexrad Split Cut Mode file

docs/history.md, docs/usage.md, examples/notebooks/Assign_GeoCoords.ipynb
Adding example for Assigning GeoCoords to Radar DataTree
Related Issue #243
=> ADD: Example for GeoCoords

docs/history.md, xradar/io/backends/nexrad_level2.py
=> FIX: correct retrieval of intermediate records in nexrad level2 reader

docs/history.md, xradar/io/backends/nexrad_level2.py
when retrieving bz2 record indices in nexradlevel2 reader
=> FIX: test for BZhX1AY&SY (where X is any number between 0..9)

docs/history.md, tests/conftest.py, tests/io/test_nexrad_level2.py, xradar/io/backends/nexrad_level2.py
=> ENH: add message 1 decoding to nexrad level2 reader

docs/history.md, tests/__init__.py, tests/io/test_io.py, xradar/io/backends/iris.py, xradar/io/backends/nexrad_level2.py
=> Implement file locking for Nexrad Level2 and IRIS/Sigmet backends

CONTRIBUTING.md, docs/history.md, requirements_dev.txt
* Add `cartopy` for test `examples/notebooks/Multi-Volume-Concatenation.ipynb`.
* Add `boto3` for test `examples/notebooks/Read-plot-Sigmet-data-from-AWS.ipynb`.
* Add `zarr` for test `examples/notebooks/multiple-sweeps-into-volume-scan.ipynb`.
* Add `s3fs` for test `examples/notebooks/Read-plot-Sigmet-data-from-AWS.ipynb`.
* Add `open_radar_data` for sample data sets used in unittests.
* Add `notebook` and `nbconvert` for unittesting jupyter notebooks.
* Add note to CONTRIBUTING.md referencing OS dependency for `ffmpeg`
=>     FIX: Add missing deps for virtualenv environments (#253)

docs/history.md, tests/test_util.py, xradar/accessors.py, xradar/util.py
The WMO conventions define two types of data variables for the sweep object:
- dataset variables, with dimension of time and range (e.g. DBZH, RR, quality1, ...)
- metadata variables, typically a scalar (e.g. sweep_number, sweep_mode, polarization_mode, ...)
These variables can be accessed together by the _data_vars_ property of the sweep object (xarray Dataset). However it is not possible to make the distinction between the two types of variables. Two new functions allow to access these variables separately.
It is possible to select dataset variables directly using sweep[list of variables]. But this results in the loss of the metadata. A new function allows to select dataset variables while keeping metadata variables.
=> ADD: function to select dataset variables in sweep

docs/history.md, tests/io/test_gamic.py, tests/test_util.py, xradar/io/backends/gamic.py, xradar/io/backends/odim.py, xradar/model.py
adds nyquist velocity as a coordinate when using the ODIM H5 and GAMIC backend
=> add nyquist_velocity as coordinate in ODIM H5/GAMIC reader

docs/history.md, tests/io/test_iris.py, xradar/io/backends/iris.py
Use correct mask for zero values. Use np.nan for unavailable values. Improve test coverage of special values.
=> Fix IRIS/Sigmet KDP decode
