- .readthedocs.yaml
- docs/conf.py
- environment.yml
Use pydata sphinx theme and read the docs
> Update env to include pydata sphinx

- .github/workflows/upload_pypi.yml
Move to enable workflow dispatch
> FIX: Move to workflow dispatch

- setup.py
Fix the markdown file in the pypi release
> FIX: Update setup file to read markdown

- .github/workflows/ci.yml
- ci/unittests.yml
- docs/_static/openradar_micro.svg
- docs/_static/openradar_mini.svg
- docs/_static/xradar_logo.svg
- docs/conf.py
- docs/history.md
- docs/usage.md
- environment.yml
- examples/notebooks/CfRadial1.ipynb
- examples/notebooks/CfRadial1_full.ipynb
- examples/notebooks/ODIM_H5.ipynb
- examples/notebooks/ODIM_H5_full.ipynb
- requirements.txt
- setup.py
- tests/conftest.py
- tests/test_io.py
- xradar/__init__.py
- xradar/io/backends/__init__.py
- xradar/io/backends/cfradial1.py
- xradar/io/backends/common.py
- xradar/io/backends/odim.py
- xradar/model.py
- xradar/util.py
This is a direct addendum of #13. Will rebase after #13 is merged.
> ODIM_H5 Backend

- CITATION.cff
- README.md
Add citation information related to Zenodo
> ENH: Add DOI to readme

- docs/conf.py
- docs/datamodel.md
- docs/history.md
- docs/importers.md
- docs/usage.md
- xradar/model.py
- adds simple datamodel description
- add direct links to standards in datamodel
- minor doc fixes
> DOC: add datamodel, minor doc fixes

- .github/workflows/ci.yml
- ci/unittests.yml
> ENH: add code coverage

- README.md
- docs/history.md
@mgrover1 How about releasing the accumulated functionality?
> REL: 0.0.8

- examples/notebooks/Furuno.ipynb
- tests/test_io.py
- xradar/io/backends/furuno.py
- align iris open-api with CfRadial1/2
- fix tests
- adapt notebook
> MIN: align furuno open-api with CfRadial1/2

- examples/notebooks/plot-ppi.ipynb
This updates the PPI example to use the new georeference accessor
> Update ppi example to use new accessor

- ci/unittests.yml
- docs/usage.md
- environment.yml
- examples/notebooks/angle_reindexing.ipynb
- requirements.txt
- tests/test_io.py
- tests/test_util.py
- xradar/io/backends/cfradial1.py
- xradar/io/backends/common.py
- xradar/io/backends/furuno.py
- xradar/io/backends/gamic.py
- xradar/io/backends/iris.py
- xradar/io/backends/odim.py
- xradar/io/backends/rainbow.py
- xradar/util.py
> ENH: Add angle reindexing util functions, add example notebook

- .github/workflows/ci.yml
- tests/georeference/test_transforms.py
- tests/test_io.py
- xradar/io/backends/cfradial1.py
- xradar/io/backends/furuno.py
- xradar/io/backends/gamic.py
- xradar/io/backends/iris.py
- xradar/io/backends/odim.py
- xradar/io/backends/rainbow.py
> ENH: make Furuno reader read WRN110 scn data (format 103)

- CITATION.cff
- docs/history.md
- Update history.md
- Update CITATION.cff
> REL: 0.0.10

- environment.yml
- xradar/io/backends/furuno.py
- xradar/io/export/odim.py
- use "sweep_fixed_angle" for furuno files
- fix to_odim attributes handling and variable writing
> FIX: use of attributes 

- CITATION.cff
- docs/history.md
Updated CITATION.cff and history.md
> REL: 0.0.11

- tests/io/test_io.py
- xradar/io/backends/odim.py
- xradar/io/export/odim.py
closes #80 
fix several issues with the odim backend
> FIX: ODIM_H5 backend inconsistencies

- CITATION.cff
- docs/history.md
> REL: 0.0.13

- docs/history.md
- tests/conftest.py
- tests/io/test_io.py
- xradar/io/export/odim.py
> ENH add mandatory source parameter to odim writer

- AUTHORS.md
- CITATION.cff
- docs/history.md
@egouden Please check, if you are happy with the attributions/affiliation. 
@mgrover1 I've set the date to March 22 to have enough time for responses.
> REL: 0.2.0

- README.md
> Update DOI badge for latest release

- docs/history.md
- environment.yml
- xradar/io/backends/furuno.py
- xradar/io/backends/gamic.py
- xradar/io/backends/iris.py
- xradar/io/backends/odim.py
> FIX: make coordinates consistent

- docs/history.md
Preparing for patch release 0.4.1.
> Release 0.4.1

- docs/history.md
> Release 0.4.2

- .pre-commit-config.yaml
- xradar/georeference/projection.py
- xradar/io/backends/furuno.py
- xradar/io/backends/iris.py
- xradar/io/backends/odim.py
- xradar/io/backends/rainbow.py
- xradar/io/export/cfradial1.py
> MNT:  address black style changes, update pre-commit-config.yaml

- docs/history.md
Update the release notes for the latest version, 0.5.0!
> DOC: Update docs for latest release 0.5.0

- docs/history.md
adds missing 0.5.1 to history.md
> add 0.5.1 to history.md

- AUTHORS.md
- CITATION.cff
- docs/history.md
- xradar/io/backends/__init__.py
- xradar/io/backends/hpl.py
> REL: 0.6.0

- .github/workflows/ci.yml
- docs/history.md
> MNT: minimize CI

- docs/history.md
To unlock #188, this is a patch release.
> REL: 0.6.1

- docs/history.md
- xradar/io/backends/odim.py
> FIX: use rstart in meter for ODIM_H5/V2_4

- docs/history.md
- xradar/io/backends/odim.py
This regression was introduced by me in #197.
> FIX: use dict.get() to retrieve attribute key and return "None" if not available

- docs/history.md
> REL: v0.6.4

- docs/history.md
This release fixes datamet processing (needed over in erad2024) and hpl lidar reader.
> REL: 0.6.5

- .github/workflows/ci.yml
- ci/notebooktests.yml
- ci/unittests.yml
- tests/io/test_cfradial1.py
- tests/io/test_datamet.py
- tests/io/test_hpl.py
- tests/io/test_io.py
- tests/io/test_nexrad_level2.py
- tests/test_accessors.py
- tests/test_util.py
- xradar/accessors.py
- xradar/georeference/projection.py
- xradar/georeference/transforms.py
- xradar/io/backends/cfradial1.py
- xradar/io/backends/common.py
- xradar/io/backends/datamet.py
- xradar/io/backends/furuno.py
- xradar/io/backends/gamic.py
- xradar/io/backends/hpl.py
- xradar/io/backends/iris.py
- xradar/io/backends/metek.py
- xradar/io/backends/nexrad_level2.py
- xradar/io/backends/odim.py
- xradar/io/backends/rainbow.py
- xradar/io/export/cfradial1.py
- xradar/io/export/cfradial2.py
- xradar/io/export/odim.py
- xradar/util.py
> Add xarray nightly CI run

- CITATION.cff
- LICENSE
- ci/notebooktests.yml
- ci/unittests.yml
- docs/history.md
- environment.yml
- requirements.txt
> Pin xarray to 2024.9.0 and release v0.7.0

- docs/history.md
- docs/usage.md
- examples/notebooks/Transform.ipynb
- tests/test_accessors.py
- tests/transform/test_cfradial.py
- xradar/__init__.py
- xradar/accessors.py
- xradar/io/export/cfradial1.py
- xradar/transform/__init__.py
- xradar/transform/cfradial.py
> ADD: Transform function CF1 to CF2 and vice versa

- docs/history.md
- tests/transform/test_cfradial.py
- xradar/io/backends/common.py
- xradar/io/export/cfradial1.py
- xradar/transform/cfradial.py
> FIX: Convert volumes to_cfradial1 containing sweeps with different range and azimuth shapes

- CITATION.cff
- LICENSE
- docs/history.md
- pyproject.toml
- tests/__init__.py
- tests/conftest.py
- tests/io/test_furuno.py
- tests/io/test_io.py
- tests/io/test_iris.py
- tests/io/test_nexrad_level2.py
- tests/io/test_rainbow.py
- xradar/io/backends/iris.py
- xradar/io/backends/nexrad_level2.py
> REL:  0.9.0

- .github/workflows/ci.yml
- .github/workflows/upload_pypi.yml
- ci/notebooktests.yml
- ci/unittests.yml
- docs/history.md
- environment.yml
- examples/notebooks/CfRadial1_Model_Transformation.ipynb
- pyproject.toml
- tests/io/test_io.py
- xradar/io/backends/cfradial1.py
> Prevent literal timedelta decoding, update pinning, fix tests

- Makefile
When calling:
make install
Use the correct command, as per documentation.
> Fix Makefile install command

- .pre-commit-config.yaml
- examples/notebooks/Accessors.ipynb
- examples/notebooks/Assign_GeoCoords.ipynb
- examples/notebooks/CfRadial1.ipynb
- examples/notebooks/CfRadial1_Export.ipynb
- examples/notebooks/CfRadial1_Model_Transformation.ipynb
- examples/notebooks/Furuno.ipynb
- examples/notebooks/GAMIC.ipynb
- examples/notebooks/HaloPhotonics.ipynb
- examples/notebooks/Iris.ipynb
- examples/notebooks/MRR.ipynb
- examples/notebooks/Mapping_Sweeps.ipynb
- examples/notebooks/Multi-Volume-Concatenation.ipynb
- examples/notebooks/NDPointIndex.ipynb
- examples/notebooks/NexradLevel2.ipynb
- examples/notebooks/ODIM_H5.ipynb
- examples/notebooks/Rainbow.ipynb
- examples/notebooks/Read-plot-Sigmet-data-from-AWS.ipynb
- examples/notebooks/Transform.ipynb
- examples/notebooks/UF.ipynb
- examples/notebooks/angle_reindexing.ipynb
- examples/notebooks/multiple-sweeps-into-volume-scan.ipynb
- examples/notebooks/plot-ppi.ipynb
> MNT: pre-commit, add metadata.language_info.pygments_lexer and metadata.language_info.version to nbstripout
